# "org" ensures this Service is used with the correct Serverless Framework Access Key.
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: meme-generator
# "service" is the name of this project. This will also be added to your AWS resource names.
service: meme-generator

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    AWS_ACCESS_KEY_ID: fakeMyKeyId
    AWS_SECRET_ACCESS_KEY: fakeSecretAccessKey
    MINIO_ENDPOINT: localhost
    MINIO_PORT: 9000
    MINIO_ACCESS_KEY: puzjXMgE4MInLD6OcR8S
    MINIO_SECRET_KEY: uJvRpWUjs3hJ3QfJDoNhQKeHP21PRseb1UQBrK8o
    MINIO_BUCKET: memebucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  uploadImage:
    handler: handler.uploadImage
    events:
      - http:
          path: upload
          method: post
          cors: true

  listMemes:
    handler: handler.listMemes
    timeout: 60
    events:
      - http:
          path: listmemes
          method: get


resources:
  Resources:
    UrlTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: key
            AttributeType: S
        KeySchema:
          - AttributeName: key
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-offline
  - serverless-dynamodb

custom:
  serverless-dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      docker: true
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
